PostgreSQL:
  restart: always
  image: postgres 
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - POSTGRES_PASSWORD=0c52788f-770c-4ddc-a6e3-19c324e1fb24
    - POSTGRES_DB=hibernate-studies-test
    - POSTGRES_USER=hibernate-studies
    - PGDATA=/vm_pg/data
    # Run 
    #  psql -h 127.0.0.1 -U hibernate-studies -d hibernate-studies-test 
    # then
    # CREATE DATABASE "hibernate-studies";
  volumes:
   - ./tmp/:/vm_pg/

